[project]
name = "django-jazzmin-addons"
version = "0.1.0a1"
description = "Django-jazzmin addons and custom templates for django applications"
readme = "README.md"
authors = [
    { name = "Jon Trigueiro", email = "joepreludian@gmail.com" }
]
requires-python = ">=3.10"
keywords = ["django", "jazzmin", "admin", "constance", "adminlte"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "django>=5.2",
    "django-jazzmin>=3.0.5",
]

[project.optional-dependencies]
django-constance = [
  "django-constance"
]
django-allauth = [
  "django-allauth"
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "jazzmin_addons"

[tool.uv.workspace]
members = [
    "test_project",
    ".",
]
